# Generated by Django 3.2.9 on 2022-07-12 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, max_length=254, upload_to='img')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
